### ISSUE TITLE
Build generates an enormous number of compiler warnings

### ISSUE THREAD

**Issue by JeremyMcCormick** [iLCSoft/LCIO#25]
Using gcc 4.8.5 there are a huge number of compiler warnings when building this project.  The build seems to complete successfully, but it is a bit alarming to see literally hundreds of warning messages when you build the project.  

Perhaps some of these compiler warnings should be turned off if this is never planned to be fixed?

**Comment by petricm** [comment]
This is a result of fairly recent decision to include `-Weffc++` in the default compiler flags for iLCSoft. Several iLCSoft packages have already been fixed not to produce warnings with this flag included and there is ongoing work to fix also the remaining. As for the particular case of LCIO I cannot tell when this is scheduled, however @gaede already fixed all warnings produced when compiling with LLVM/Clang, so there is certainly movement in this direction and it would be wise to retain this flag. 

I would like to further point out that it was also agreed that new developments in iLCSoft are not necessarily `C++98` complaint as the default standard is now `C++11`. GCC 4.8 series only provides experimental support for `C++11` (as per [release notes](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html)), for instance the 4.8 series features an incomplete `<regex>` implementation, which is only fixed in 4.9 (see [bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631)), which is also the lowest version of GCC that has a full `C++11` compliant implementation. It might be that code works now with 4.8, but this might not be necessarily true for the future and I would advise you to use at least GCC 4.9.

**Comment by gaede** [comment]
All warnings are fixed with llvm and gcc6. There will still be warnings with gcc4.8 but they can be ignored.
