### ISSUE TITLE
Use standard CMake Variables instead of USE_CXX11

### ISSUE THREAD

**Issue by vvolkl** [iLCSoft/LCIO#78]
The custom option `USE_CXX11` should be replaced by `CMAKE_CXX_STANDARD`.

**Comment by rete** [comment]
Hi,
in principle, one could specify `-DUSE_CXX11=OFF` and `-DCMAKE_CXX_STANDARD=17`. This is what we currently do in our installation scripts for iLCSoft and it works like a charm.
But I agree, this CMake variable `USE_CXX11` should be remove. The problem is that this variable is part of iLCUtil and used in many other projects to set the CXX standard to 11. The cleanup is thus a bit more complicated.
I close this issue as a workaround exists, but feel free to open a new one in iLCUtil if you still have a problem related to this.
Thanks

**Comment by vvolkl** [comment]
Thanks for the explanation, that works for me.
